-- MySQL Script generated by MySQL Workbench
-- Thu 10 Nov 2022 05:53:59 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RWA2022nmidzic20
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RWA2022nmidzic20
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RWA2022nmidzic20` ;
USE `RWA2022nmidzic20` ;

-- -----------------------------------------------------
-- Table `RWA2022nmidzic20`.`tip_korisnika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RWA2022nmidzic20`.`tip_korisnika` ;

CREATE TABLE IF NOT EXISTS `RWA2022nmidzic20`.`tip_korisnika` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `naziv_UNIQUE` (`naziv` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RWA2022nmidzic20`.`korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RWA2022nmidzic20`.`korisnik` ;

CREATE TABLE IF NOT EXISTS `RWA2022nmidzic20`.`korisnik` (
  `korime` VARCHAR(30) NOT NULL,
  `ime` VARCHAR(50) NOT NULL,
  `prezime` VARCHAR(100) NOT NULL,
  `lozinka` TEXT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `tip_korisnika_id` INT NOT NULL,
  `aktivan` TINYINT(1) NOT NULL,
  `blokiran` TINYINT(1) NOT NULL,
  `datum_registracije` DATETIME NOT NULL,
  `aktivacijski_kod` TEXT NOT NULL,
  `totp` TEXT NOT NULL,
  UNIQUE INDEX `korime_UNIQUE` (`korime` ASC),
  PRIMARY KEY (`korime`),
  INDEX `fk_korisnik_tip_korisnika1_idx` (`tip_korisnika_id` ASC),
  CONSTRAINT `fk_korisnik_tip_korisnika1`
    FOREIGN KEY (`tip_korisnika_id`)
    REFERENCES `RWA2022nmidzic20`.`tip_korisnika` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RWA2022nmidzic20`.`film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RWA2022nmidzic20`.`film` ;

CREATE TABLE IF NOT EXISTS `RWA2022nmidzic20`.`film` (
  `tmdb_id` INT NOT NULL,
  `naziv` TEXT NOT NULL,
  `korisnik_dodao` VARCHAR(30) NOT NULL,
  `datum_dodan` DATETIME NOT NULL,
  `odobren` TINYINT(1) NOT NULL,
  `odrasli_film` TINYINT(1) NULL,
  `putanja_pozadine` TEXT NULL,
  `budzet` VARCHAR(15) NULL,
  `pocetna_stranica` TEXT NULL,
  `imdb_id` INT NULL,
  `originalni_jezik` VARCHAR(5) NULL,
  `originalni_naslov` TEXT NULL,
  `sazetak` TEXT NULL,
  `popularnost` VARCHAR(10) NULL,
  `putanja_postera` TEXT NULL,
  `datum_izlaska` DATETIME NULL,
  `prihod` VARCHAR(20) NULL,
  `trajanje` INT NULL,
  `status` VARCHAR(20) NULL,
  `slogan` TEXT NULL,
  `video` TINYINT(1) NULL,
  `prosjek_glasova` DECIMAL NULL,
  `broj_glasova` INT NULL,
  PRIMARY KEY (`tmdb_id`),
  UNIQUE INDEX `tmdb_id_UNIQUE` (`tmdb_id` ASC),
  INDEX `fk_film_korisnik1_idx` (`korisnik_dodao` ASC),
  CONSTRAINT `fk_film_korisnik1`
    FOREIGN KEY (`korisnik_dodao`)
    REFERENCES `RWA2022nmidzic20`.`korisnik` (`korime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RWA2022nmidzic20`.`zanr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RWA2022nmidzic20`.`zanr` ;

CREATE TABLE IF NOT EXISTS `RWA2022nmidzic20`.`zanr` (
  `z_tmdb_id` INT NOT NULL AUTO_INCREMENT,
  `z_naziv` VARCHAR(50) NOT NULL,
  `originalni_naziv` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`z_tmdb_id`),
  UNIQUE INDEX `naziv_UNIQUE` (`z_naziv` ASC),
  UNIQUE INDEX `originalni_naziv_UNIQUE` (`originalni_naziv` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RWA2022nmidzic20`.`film_zanr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RWA2022nmidzic20`.`film_zanr` ;

CREATE TABLE IF NOT EXISTS `RWA2022nmidzic20`.`film_zanr` (
  `zanr_id` INT NOT NULL,
  `film_id` INT NOT NULL,
  PRIMARY KEY (`zanr_id`, `film_id`),
  INDEX `fk_zanr_has_film_film1_idx` (`film_id` ASC),
  INDEX `fk_zanr_has_film_zanr1_idx` (`zanr_id` ASC),
  CONSTRAINT `fk_zanr_has_film_zanr1`
    FOREIGN KEY (`zanr_id`)
    REFERENCES `RWA2022nmidzic20`.`zanr` (`z_tmdb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zanr_has_film_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `RWA2022nmidzic20`.`film` (`tmdb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
